name: Scheduled API Fetch

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Download required files
        run: |
          curl --silent -O https://raw.githubusercontent.com/${{ github.repository }}/main/main.py
          curl --silent -O https://raw.githubusercontent.com/${{ github.repository }}/main/requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Install dependencies and run script
        run: |
          pip install -r requirements.txt
          python main.py
        env:
          HOSTED_API: ${{ secrets.HOSTED_API }}